language: r
sudo: required
cache: packages
dist: trusty
r:
    - oldrel
    - release
    - devel
r_binary_packages:
    - devtools
    - testthat
    - roxygen2
    - crayon
    - r6
r_github_packages:
    - robertzk/bettertrace
    - robertzk/testthatsomemore
    - syberia/stagerunner
    - syberia/director
    - kirillseva/covr
    - hadley/purrr

after_success:
  - "Rscript -e 'library(covr);coveralls()'"
notifications:
  webhooks:
    urls:
       - https://webhooks.gitter.im/e/655fbe5e7a5067377f3f
  email:
    on_success: change
    on_failure: change
  hipchat:
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
  rooms:
    secure: l+wmlZJjYTD9Gv+oSp+y5IE6UFAwGEbfiUdoIU8VA4AihIsarEu9/h1WfuZLf00qlxktx45BLsecvn5QGX+IHVTXDFxmYyL+pzuTdNYZjc87EutstyJ1Ahdt5IA49A8X+PHAO7v60XIjrUrXPKwx3vxsVmO1RSayo0xAwfnupmk= 
env:
  - global:
    - CI=TRUE
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
